"""
src/dns.py — DNS Namespace Controller
=======================================
Manages /etc/resolv.conf to force all DNS resolution through Tor's
local DNS resolver (127.0.0.1:9053).

The critical operation here is the ``chattr +i`` immutable flag, which
prevents NetworkManager, systemd-resolved, and DHCP clients from
overwriting our locked configuration while the VPN is active.
"""

import logging
import shutil
import subprocess
from pathlib import Path

log = logging.getLogger("torvpn.dns")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
RESOLV_CONF = Path("/etc/resolv.conf")
RESOLV_BACKUP = Path("/etc/resolv.conf.torvpn.bak")

# The locked resolv.conf content — only Tor's DNS resolver.
LOCKED_CONTENT = """\
# Generated by torvpn — DNS locked to Tor resolver.
# This file is immutable (chattr +i) while torvpn is active.
# DO NOT edit manually — use torvpn to manage this file.
nameserver 127.0.0.1
"""


# ---------------------------------------------------------------------------
# Module state
# ---------------------------------------------------------------------------
_backup_created = False
_was_symlink = False
_symlink_target = ""


# ---------------------------------------------------------------------------
# Helper: run chattr
# ---------------------------------------------------------------------------
def _chattr(flag: str) -> None:
    """Set or remove the immutable attribute on resolv.conf.

    Args:
        flag: "+i" to set immutable, "-i" to remove it.
    """
    cmd = ["chattr", flag, str(RESOLV_CONF)]
    log.debug("exec: %s", " ".join(cmd))
    subprocess.run(
        cmd,
        check=True,
        capture_output=True,
        text=True,
        timeout=10,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def lock() -> None:
    """Lock DNS resolution to Tor's local resolver.

    Sequence:
        1. Remove any existing immutable flag (idempotent safety).
        2. Back up the current resolv.conf.
        3. Write our locked nameserver configuration.
        4. Set the immutable flag to prevent overwriting.

    This must be called AFTER the Tor daemon is running and AFTER
    the nftables rules are in place, so DNS queries to 127.0.0.1
    are actually handled by Tor's DNSPort.
    """
    global _backup_created, _was_symlink, _symlink_target

    log.info("=" * 50)
    log.info("DNS — LOCKING RESOLVER")
    log.info("=" * 50)

    # Step 1: Remove immutable flag if it exists (from a previous crash, etc.)
    try:
        _chattr("-i")
        log.debug("Cleared pre-existing immutable flag")
    except subprocess.CalledProcessError:
        # Flag wasn't set — that's fine
        log.debug("No pre-existing immutable flag to clear")

    # Step 2: Back up current resolv.conf
    if RESOLV_CONF.exists():
        # If the file is a symlink (common with systemd-resolved),
        # we need to copy the actual content, not the symlink itself.
        if RESOLV_CONF.is_symlink():
            _was_symlink = True
            _symlink_target = os.readlink(str(RESOLV_CONF))
            # Read the symlink target's content and write it to the backup
            content = RESOLV_CONF.read_text()
            RESOLV_BACKUP.write_text(content)
            log.info("Backed up resolv.conf (was symlink pointing to %s) → %s", _symlink_target, RESOLV_BACKUP)
            # Remove the symlink so we can write a regular file
            RESOLV_CONF.unlink()
        else:
            _was_symlink = False
            _symlink_target = ""
            shutil.copy2(str(RESOLV_CONF), str(RESOLV_BACKUP))
            log.info("Backed up resolv.conf → %s", RESOLV_BACKUP)

        _backup_created = True
    else:
        log.warning("No existing resolv.conf found — creating fresh")
        _backup_created = False
        _was_symlink = False
        _symlink_target = ""

    # Step 3: Write locked DNS configuration
    RESOLV_CONF.write_text(LOCKED_CONTENT)
    log.info("Wrote locked resolv.conf: nameserver 127.0.0.1")

    # Step 4: Set immutable flag
    _chattr("+i")
    log.info("[OK] resolv.conf locked (immutable flag set)")
    log.info("     NetworkManager and systemd-resolved cannot override DNS")


def restore() -> None:
    """Restore the original resolv.conf and remove the immutable lock.

    Sequence:
        1. Remove immutable flag.
        2. Restore from backup (if backup exists).
        3. Clean up backup file.

    Errors are logged but not re-raised — teardown should be as
    resilient as possible.
    """
    log.info("=" * 50)
    log.info("DNS — RESTORING RESOLVER")
    log.info("=" * 50)

    # Step 1: Remove immutable flag
    try:
        _chattr("-i")
        log.info("Removed immutable flag from resolv.conf")
    except subprocess.CalledProcessError as exc:
        log.warning("Could not remove immutable flag: %s", exc)

    # Step 2: Restore from backup
    if _backup_created:
        try:
            if _was_symlink and _symlink_target:
                RESOLV_CONF.unlink(missing_ok=True)
                os.symlink(_symlink_target, str(RESOLV_CONF))
                log.info("[OK] Restored original resolv.conf symlink pointing to %s", _symlink_target)
            elif RESOLV_BACKUP.exists():
                shutil.copy2(str(RESOLV_BACKUP), str(RESOLV_CONF))
                log.info("[OK] Restored original resolv.conf from backup")
        except OSError as exc:
            log.error("Failed to restore resolv.conf: %s", exc)

        # Step 3: Clean up backup
        if RESOLV_BACKUP.exists():
            try:
                RESOLV_BACKUP.unlink()
                log.debug("Removed backup file: %s", RESOLV_BACKUP)
            except OSError as exc:
                log.warning("Could not remove backup file: %s", exc)
    else:
        log.warning(
            "No backup file found at %s — resolv.conf may need manual restoration",
            RESOLV_BACKUP,
        )

    log.info("[OK] DNS resolver unlocked")


def restore_from_backup(original_resolv_content: str) -> None:
    """Restore resolv.conf from a backup data string.

    This is the disaster-recovery path used by ``backup.disaster_recovery()``
    when a stale backup file is found on startup.  It does NOT rely on the
    sidecar ``.torvpn.bak`` file or the module-level ``_backup_created`` flag.

    Sequence:
        1. Remove immutable flag (may have been set by a previous lock()).
        2. Write the original content back to /etc/resolv.conf.

    Args:
        original_resolv_content: The original resolv.conf file contents
                                 as stored in the persistent JSON backup.
    """
    log.info("Restoring resolv.conf from persistent backup data...")

    # Step 1: Remove immutable flag
    try:
        _chattr("-i")
        log.debug("Cleared immutable flag for disaster recovery")
    except subprocess.CalledProcessError:
        log.debug("No immutable flag to clear")

    # Step 2: Write original content
    RESOLV_CONF.write_text(original_resolv_content)
    log.info("[OK] resolv.conf restored from backup data")
